#!/bin/sh
# DKKim 20140825
# remove remote git branch# script to convert a branch to a tag
# then delete branch
# usage: branch_to_tag $BRANCHNAME


# exit script on any error
set -e

# make sure we're not on the branch to delete
CURRENT=`basename $(git symbolic-ref HEAD)`
echo current branch is: $CURRENT
if [ $CURRENT = $1 ]
  then
    echo Cannot delete the current branch, pick another and try again.
    exit 1;
fi

# get the specific SHA hash of the commit to which the branch points
REF1=`git show-ref --heads --hash "$1"`
echo branch found: $1
echo corresponds to SHA: $REF1

# create a tag at this specific commit
git tag $1 $REF1
echo tag created
# delete the branch pointer
git branch -D $1
echo branch deleted